---
# https://docs.gitlab.com/ee/ci/docker/using_docker_build.html

stages:
  - commit
  - syntax
  - docker

# commit
git-history:
  stage: commit
  script:
    - >
      bash <(curl -s
      https://gitlab.com/yue-script/checks/raw/master/check_git_history.sh)

lines-length:
  stage: commit
  script:
    - >
      bash <(curl -s
      https://gitlab.com/yue-script/checks/raw/master/check_lines_length.sh)

# syntax
docker-lint:
  stage: syntax
  image: vpgrp/nodejs:latest
  before_script:
    - npm install -g dockerlint
  script:
    - dockerlint ansible/Dockerfile
    - dockerlint docker/Dockerfile
    - dockerlint golang/Dockerfile
    - dockerlint json/Dockerfile
    - dockerlint php/Dockerfile
    - dockerlint puppet/Dockerfile
    - dockerlint python/Dockerfile
    - dockerlint ruby/Dockerfile
    - dockerlint shell/Dockerfile
    - dockerlint yaml/Dockerfile

# docker
build-ansible:
  stage: docker
  image: docker:latest
  services:
    - docker:dind
  variables:
    DOCKER_DRIVER: overlay
  script:
    - docker build --rm ansible

build-docker:
  stage: docker
  image: docker:latest
  services:
    - docker:dind
  variables:
    DOCKER_DRIVER: overlay
  script:
    - docker build --rm docker

build-golang:
  stage: docker
  image: docker:latest
  services:
    - docker:dind
  variables:
    DOCKER_DRIVER: overlay
  script:
    - docker build --rm golang

build-json:
  stage: docker
  image: docker:latest
  services:
    - docker:dind
  variables:
    DOCKER_DRIVER: overlay
  script:
    - docker build --rm json

build-php:
  stage: docker
  image: docker:latest
  services:
    - docker:dind
  variables:
    DOCKER_DRIVER: overlay
  script:
    - docker build --rm php

build-puppet:
  stage: docker
  image: docker:latest
  services:
    - docker:dind
  variables:
    DOCKER_DRIVER: overlay
  script:
    - docker build --rm puppet

build-python:
  stage: docker
  image: docker:latest
  services:
    - docker:dind
  variables:
    DOCKER_DRIVER: overlay
  script:
    - docker build --rm python

build-ruby:
  stage: docker
  image: docker:latest
  services:
    - docker:dind
  variables:
    DOCKER_DRIVER: overlay
  script:
    - docker build --rm ruby

build-shell:
  stage: docker
  image: docker:latest
  services:
    - docker:dind
  variables:
    DOCKER_DRIVER: overlay
  script:
    - docker build --rm shell

build-yaml:
  stage: docker
  image: docker:latest
  services:
    - docker:dind
  variables:
    DOCKER_DRIVER: overlay
  script:
    - docker build --rm yaml
# EOF
